# ======================================================================= #
#  Copyright (C) 2020 - 2025 Dominik Willner <th33xitus@gmail.com>        #
#                                                                         #
#  This file is part of KIAUH - Klipper Installation And Update Helper    #
#                                                                         #
#  This file may be distributed under the terms of the GNU GPLv3 license  #
# ======================================================================= #
"""
APT 镜像源自动切换模块
支持 Debian、Ubuntu、Raspberry Pi OS 等主流发行版
"""
from __future__ import annotations

import shutil
from datetime import datetime
from pathlib import Path
from subprocess import run, CalledProcessError, PIPE
from typing import Dict, List, Tuple, Optional

from core.logger import Logger, DialogType
from utils.input_utils import get_confirm


# 中国大陆主流镜像源配置
CHINA_MIRRORS = {
    "tsinghua": {
        "name": "清华大学 TUNA",
        "url": "https://mirrors.tuna.tsinghua.edu.cn",
    },
    "aliyun": {
        "name": "阿里云",
        "url": "https://mirrors.aliyun.com",
    },
    "ustc": {
        "name": "中国科学技术大学",
        "url": "https://mirrors.ustc.edu.cn",
    },
    "tencent": {
        "name": "腾讯云",
        "url": "https://mirrors.tencent.com",
    },
}

# Debian/Ubuntu 发行版代号
DEBIAN_VERSIONS = {
    "11": "bullseye",
    "12": "bookworm",
    "10": "buster",
}

UBUNTU_VERSIONS = {
    "22.04": "jammy",
    "20.04": "focal",
    "24.04": "noble",
}


def detect_os_info() -> Tuple[str, str, str]:
    """
    检测操作系统信息
    :return: (distro_id, distro_version, distro_codename)
    """
    try:
        with open("/etc/os-release") as f:
            os_info = {}
            for line in f:
                if "=" in line:
                    key, value = line.strip().split("=", 1)
                    os_info[key] = value.strip('"')

        distro_id = os_info.get("ID", "").lower()
        distro_version = os_info.get("VERSION_ID", "").strip('"')
        distro_codename = os_info.get("VERSION_CODENAME", "")

        # Raspberry Pi OS 使用 Debian 的 ID
        if distro_id == "raspbian":
            distro_id = "debian"

        return distro_id, distro_version, distro_codename

    except Exception as e:
        Logger.print_error(f"无法检测操作系统信息 / Cannot detect OS info: {e}")
        return "", "", ""


def is_supported_os(distro_id: str, distro_version: str) -> bool:
    """
    检查是否支持当前操作系统
    :return: True if supported
    """
    if distro_id == "debian":
        # 提取主版本号
        major_version = distro_version.split(".")[0]
        return major_version in DEBIAN_VERSIONS

    elif distro_id == "ubuntu":
        return distro_version in UBUNTU_VERSIONS

    return False


def get_codename(distro_id: str, distro_version: str, detected_codename: str) -> str:
    """
    获取发行版代号
    :return: codename (e.g., bullseye, jammy)
    """
    if detected_codename:
        return detected_codename

    if distro_id == "debian":
        major_version = distro_version.split(".")[0]
        return DEBIAN_VERSIONS.get(major_version, "")

    elif distro_id == "ubuntu":
        return UBUNTU_VERSIONS.get(distro_version, "")

    return ""


def generate_sources_list(
    distro_id: str,
    codename: str,
    mirror_key: str = "tsinghua"
) -> str:
    """
    生成 sources.list 内容
    :param distro_id: 发行版 ID (debian/ubuntu)
    :param codename: 版本代号 (bullseye/jammy/etc)
    :param mirror_key: 镜像源键名
    :return: sources.list 内容
    """
    mirror = CHINA_MIRRORS.get(mirror_key, CHINA_MIRRORS["tsinghua"])
    mirror_url = mirror["url"]

    if distro_id == "debian":
        return f"""# Debian {codename} 镜像源 - {mirror['name']}
# Generated by KIAUH at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

deb {mirror_url}/debian/ {codename} main contrib non-free
deb {mirror_url}/debian/ {codename}-updates main contrib non-free
deb {mirror_url}/debian/ {codename}-backports main contrib non-free

# Debian Security
deb https://security.debian.org/debian-security {codename}-security main contrib non-free

# 源码仓库（通常不需要，已注释）
# deb-src {mirror_url}/debian/ {codename} main contrib non-free
# deb-src {mirror_url}/debian/ {codename}-updates main contrib non-free
"""

    elif distro_id == "ubuntu":
        return f"""# Ubuntu {codename} 镜像源 - {mirror['name']}
# Generated by KIAUH at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

deb {mirror_url}/ubuntu/ {codename} main restricted universe multiverse
deb {mirror_url}/ubuntu/ {codename}-updates main restricted universe multiverse
deb {mirror_url}/ubuntu/ {codename}-backports main restricted universe multiverse

# Ubuntu Security
deb {mirror_url}/ubuntu/ {codename}-security main restricted universe multiverse

# 源码仓库（通常不需要，已注释）
# deb-src {mirror_url}/ubuntu/ {codename} main restricted universe multiverse
"""

    return ""


def backup_sources_list() -> Path:
    """
    备份当前的 sources.list
    :return: 备份文件路径
    """
    sources_file = Path("/etc/apt/sources.list")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_file = Path(f"/etc/apt/sources.list.bak_{timestamp}")

    try:
        Logger.print_status("备份原有 sources.list / Backing up sources.list...")

        # 使用 sudo cp 备份
        run(
            ["sudo", "cp", str(sources_file), str(backup_file)],
            check=True,
            stderr=PIPE,
        )

        Logger.print_ok(f"备份已保存 / Backup saved: {backup_file}")
        return backup_file

    except CalledProcessError as e:
        Logger.print_error(f"备份失败 / Backup failed: {e}")
        raise


def write_sources_list(content: str) -> bool:
    """
    写入新的 sources.list
    :param content: 新的 sources.list 内容
    :return: True if successful
    """
    try:
        Logger.print_status("写入新的镜像源配置 / Writing new mirror configuration...")

        # 使用 sudo tee 写入
        result = run(
            ["sudo", "tee", "/etc/apt/sources.list"],
            input=content.encode(),
            stdout=PIPE,
            stderr=PIPE,
            check=True,
        )

        Logger.print_ok("镜像源配置已更新 / Mirror configuration updated!")
        return True

    except CalledProcessError as e:
        Logger.print_error(f"写入失败 / Write failed: {e}")
        return False


def update_apt_cache() -> bool:
    """
    更新 APT 缓存
    :return: True if successful
    """
    try:
        Logger.print_status("更新软件包列表 / Updating package lists...")

        result = run(
            ["sudo", "apt-get", "update", "--allow-releaseinfo-change"],
            check=True,
            stderr=PIPE,
        )

        Logger.print_ok("软件包列表更新成功 / Package lists updated successfully!")
        return True

    except CalledProcessError as e:
        Logger.print_error(f"更新失败 / Update failed: {e}")
        return False


def list_available_mirrors() -> List[str]:
    """
    列出可用的镜像源
    :return: 镜像源键名列表
    """
    return list(CHINA_MIRRORS.keys())


def get_mirror_info(mirror_key: str) -> Dict[str, str]:
    """
    获取镜像源信息
    :param mirror_key: 镜像源键名
    :return: 镜像源信息字典
    """
    return CHINA_MIRRORS.get(mirror_key, {})


def restore_from_backup(backup_file: Path) -> bool:
    """
    从备份恢复 sources.list
    :param backup_file: 备份文件路径
    :return: True if successful
    """
    try:
        Logger.print_status("从备份恢复 / Restoring from backup...")

        run(
            ["sudo", "cp", str(backup_file), "/etc/apt/sources.list"],
            check=True,
            stderr=PIPE,
        )

        Logger.print_ok("已恢复原有配置 / Original configuration restored!")
        return True

    except CalledProcessError as e:
        Logger.print_error(f"恢复失败 / Restore failed: {e}")
        return False


def switch_apt_mirror_auto(mirror_key: str = "tsinghua") -> bool:
    """
    自动切换 APT 镜像源（核心函数）
    :param mirror_key: 镜像源键名（默认清华）
    :return: True if successful
    """
    Logger.print_status("\n═══ APT 镜像源自动切换 / APT Mirror Auto-Switch ═══\n")

    # 1. 检测操作系统
    distro_id, distro_version, detected_codename = detect_os_info()

    if not distro_id or not distro_version:
        Logger.print_error("无法检测操作系统信息 / Cannot detect OS information")
        return False

    Logger.print_info(f"检测到操作系统 / Detected OS: {distro_id} {distro_version}")

    # 2. 检查是否支持
    if not is_supported_os(distro_id, distro_version):
        Logger.print_error(
            f"暂不支持此操作系统 / OS not supported: {distro_id} {distro_version}"
        )
        Logger.print_info("支持的系统 / Supported systems:")
        Logger.print_info("  • Debian 10/11/12 (Buster/Bullseye/Bookworm)")
        Logger.print_info("  • Ubuntu 20.04/22.04/24.04 (Focal/Jammy/Noble)")
        return False

    # 3. 获取代号
    codename = get_codename(distro_id, distro_version, detected_codename)
    if not codename:
        Logger.print_error("无法确定版本代号 / Cannot determine codename")
        return False

    Logger.print_info(f"版本代号 / Codename: {codename}")

    # 4. 显示将使用的镜像源
    mirror_info = get_mirror_info(mirror_key)
    Logger.print_info(f"\n将使用镜像源 / Will use mirror: {mirror_info['name']}")
    Logger.print_info(f"镜像地址 / Mirror URL: {mirror_info['url']}")

    # 5. 确认操作
    Logger.print_dialog(
        DialogType.WARNING,
        [
            "此操作将修改系统的 APT 软件源配置",
            "This will modify your system's APT sources configuration",
            "\n",
            "操作步骤 / Steps:",
            "  1. 备份当前配置到 /etc/apt/sources.list.bak_*",
            "     Backup current config to /etc/apt/sources.list.bak_*",
            "  2. 写入新的镜像源配置",
            "     Write new mirror configuration",
            "  3. 更新软件包列表",
            "     Update package lists",
            "\n",
            "如需恢复，可使用备份文件",
            "You can restore from backup if needed",
        ],
    )

    if not get_confirm(
        "确认切换 APT 镜像源？ / Confirm APT mirror switch?",
        default_choice=True,
    ):
        Logger.print_info("操作已取消 / Operation cancelled")
        return False

    # 6. 备份原有配置
    try:
        backup_file = backup_sources_list()
    except Exception as e:
        Logger.print_error(f"备份失败，停止操作 / Backup failed, aborting: {e}")
        return False

    # 7. 生成新配置
    new_sources_content = generate_sources_list(distro_id, codename, mirror_key)

    # 8. 写入新配置
    if not write_sources_list(new_sources_content):
        Logger.print_error("写入配置失败 / Failed to write configuration")
        # 尝试恢复
        restore_from_backup(backup_file)
        return False

    # 9. 更新 APT 缓存
    if not update_apt_cache():
        Logger.print_warn(
            "APT 缓存更新失败，但镜像源已切换 / "
            "APT update failed, but mirror switched"
        )
        Logger.print_info(
            "您可以稍后手动运行：sudo apt-get update\n"
            "You can run manually later: sudo apt-get update"
        )

    # 10. 完成
    Logger.print_dialog(
        DialogType.CUSTOM,
        custom_title="APT 镜像源切换成功！ / APT Mirror Switched!",
        custom_color="green",
        content=[
            f"已切换至：{mirror_info['name']}",
            f"Switched to: {mirror_info['name']}",
            "\n",
            f"备份文件 / Backup file: {backup_file}",
            "\n",
            "如需恢复原有配置 / To restore original config:",
            f"  sudo cp {backup_file} /etc/apt/sources.list",
            f"  sudo apt-get update",
        ],
    )

    return True


def show_apt_mirror_menu() -> None:
    """
    显示 APT 镜像选择菜单
    """
    Logger.print_status("\n═══ 选择 APT 镜像源 / Select APT Mirror ═══\n")

    mirrors = list_available_mirrors()

    Logger.print_info("可用镜像源 / Available mirrors:\n")
    for i, mirror_key in enumerate(mirrors, 1):
        mirror_info = get_mirror_info(mirror_key)
        Logger.print_info(f"  {i}) {mirror_info['name']}")
        Logger.print_info(f"     {mirror_info['url']}\n")

    Logger.print_info("  0) 取消 / Cancel\n")

    try:
        choice = input("请选择 / Please choose [1]: ").strip() or "1"

        if choice == "0":
            Logger.print_info("操作已取消 / Operation cancelled")
            return

        choice_idx = int(choice) - 1
        if 0 <= choice_idx < len(mirrors):
            mirror_key = mirrors[choice_idx]
            switch_apt_mirror_auto(mirror_key)
        else:
            Logger.print_error("无效选择 / Invalid choice")

    except ValueError:
        Logger.print_error("无效输入 / Invalid input")
    except KeyboardInterrupt:
        Logger.print_info("\n操作已取消 / Operation cancelled")


def list_backups() -> List[Path]:
    """
    列出所有 sources.list 备份文件
    :return: 备份文件列表
    """
    sources_dir = Path("/etc/apt")
    backups = sorted(sources_dir.glob("sources.list.bak_*"), reverse=True)
    return list(backups)


def show_backup_restore_menu() -> None:
    """
    显示备份恢复菜单
    """
    Logger.print_status("\n═══ 恢复 APT 镜像源备份 / Restore APT Mirror Backup ═══\n")

    backups = list_backups()

    if not backups:
        Logger.print_info("未找到备份文件 / No backup files found")
        return

    Logger.print_info("可用备份 / Available backups:\n")
    for i, backup in enumerate(backups, 1):
        # 从文件名提取时间戳
        timestamp = backup.stem.replace("sources.list.bak_", "")
        formatted_time = f"{timestamp[:4]}-{timestamp[4:6]}-{timestamp[6:8]} {timestamp[9:11]}:{timestamp[11:13]}:{timestamp[13:15]}"
        Logger.print_info(f"  {i}) {formatted_time}")
        Logger.print_info(f"     {backup}\n")

    Logger.print_info("  0) 取消 / Cancel\n")

    try:
        choice = input("请选择要恢复的备份 / Choose backup to restore [0]: ").strip() or "0"

        if choice == "0":
            Logger.print_info("操作已取消 / Operation cancelled")
            return

        choice_idx = int(choice) - 1
        if 0 <= choice_idx < len(backups):
            backup_file = backups[choice_idx]

            if get_confirm(
                f"确认恢复此备份？ / Confirm restore this backup?\n{backup_file}",
                default_choice=False,
            ):
                if restore_from_backup(backup_file):
                    update_apt_cache()
        else:
            Logger.print_error("无效选择 / Invalid choice")

    except ValueError:
        Logger.print_error("无效输入 / Invalid input")
    except KeyboardInterrupt:
        Logger.print_info("\n操作已取消 / Operation cancelled")
